name: Build Python App
description: ""

runs:
  using: composite
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install -U pyinstaller
        pip install pyyaml jsonschema colorama windows-curses
    - name: Build executable
      shell: cmd
      run: |
        pyinstaller ./MeteorShowerIdentificationConsole/meteors.spec --noconfirm