# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build meteors.exe

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  python-exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Python executable
      uses: "./.github/steps/build_python"
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          dist/meteors/meteors.exe
