name: "Compile LaTeX"
on: [workflow_dispatch]
env:
  ROOT_FILE: MFF-BP-Ciesla-Michal
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v4
      - name: "Install TeXLive"
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            scheme-basic starfont pdfx babel lmodrn fontenc textcomp inputenc amsmath amsfonts amsthm bbding bm graphicx fancyvrb caption
            indentfirst bookmark dcolumn booktabs paralist xcolor csquotes biblatex enumitem amssymb pifont environ tocbibind xmpincl
      - name: "Compile LaTeX document"
        run: |
          cd Thesis/
          latexmk -pdf ${{ env.ROOT_FILE }}.tex -interaction=nonstopmode
      - name: "Upload PDF"
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "Thesis PDF"
          path: "Thesis/${{ env.ROOT_FILE }}.pdf"
          compression-level: 0
          overwrite: true
