name: "Compile LaTeX"
on:
  push:
    tags:
      - "draft*"
      - "final*"
  workflow_dispatch:
env:
  ROOT_FILE: MFF-BP-Ciesla-Michal
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v4
      # - name: "Install TeXLive"
      #   uses: zauguin/install-texlive@v3
      #   with:
      #     packages: >
      #       scheme-basic starfont pdfx babel lmodrn fontenc textcomp inputenc amsmath amsfonts amsthm bbding bm graphicx fancyvrb caption
      #       indentfirst bookmark dcolumn booktabs paralist xcolor csquotes biblatex enumitem amssymb pifont environ tocbibind xmpincl
      # - name: "Compile LaTeX document"
      #   run: |
      #     cd Thesis/
      #     latexmk -pdf ${{ env.ROOT_FILE }}.tex -interaction=nonstopmode
      - name: "Compile LaTeX document"
        uses: dante-ev/latex-action@latest
        with:
          root_file: Thesis/${{ env.ROOT_FILE }}.tex
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/draft') || startsWith(github.ref, 'refs/tags/final')
        with:
          files: |
            Thesis/${{ env.ROOT_FILE }}.pdf
