name: "Compile thesis PDF"
on:
  push:
    tags:
      - "draft*"
      - "final*"
  workflow_dispatch:
permissions:
  contents: write
env:
  ROOT_FILE: MFF-BP-Ciesla-Michal
jobs:
  thesis-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Git repository"
        uses: actions/checkout@v4
      - name: "Compile LaTeX document"
        uses: dante-ev/latex-action@latest
        with:
          working_directory: Thesis/
          root_file: ${{ env.ROOT_FILE }}.tex
      - name: Build Python executable
        uses: "./.github/steps/build_python"
      - name: Upload PDF and logs
        uses: actions/upload-artifact@v4
        with:
          name: "latexmk-results"
          path: |
            Thesis/${{ env.ROOT_FILE }}.pdf
            Thesis/${{ env.ROOT_FILE }}.log
            dist/meteors/meteors.exe
          compression-level: 0
          overwrite: true
          retention-days: 5
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/draft')
        with:
          files: |
            Thesis/${{ env.ROOT_FILE }}.pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/final')
        with:
          files: |
            Thesis/${{ env.ROOT_FILE }}.pdf
            dist/meteors/meteors.exe
